using System.Net;
using Bunit;
using Microsoft.AspNetCore.Components;
using XN1Lab.Platform.Api.Exceptions;
using XN1Lab.XN1Finance.Tracking.Tests.Fixtures;
using XN1Lab.XN1Finance.PortfolioAnalytics.Web.Features.Tracking.Components;
using XN1Lab.XN1Finance.PortfolioAnalytics.Web.Features.Tracking.Models;
namespace XN1Lab.XN1Finance.Tracking.Tests;
public sealed class TrackingPlanEditorTests
{
 [Fact] public void Editing_clones_definition_and_does_not_mutate_loaded_plan(){using var ctx=new TrackingTestContext();var cut=ctx.Render<TrackingPlanEditor>(p=>p.Add(x=>x.Plan,ctx.Api.Plan));cut.WaitForAssertion(()=>Assert.NotEmpty(cut.FindAll("form")));var original=ctx.Api.Plan.CurrentVersion!.Definition.Indicators[0].Parameters["period"];var period=cut.FindAll("input[type=number]").First(x=>x.GetAttribute("value")=="14");period.Change("21");Assert.Equal(original,ctx.Api.Plan.CurrentVersion.Definition.Indicators[0].Parameters["period"]);Assert.Null(ctx.Api.SavedRequest);}
 [Fact] public void Save_revalidates_and_sends_pinned_revision_without_activation(){using var ctx=new TrackingTestContext();var cut=ctx.Render<TrackingPlanEditor>(p=>p.Add(x=>x.Plan,ctx.Api.Plan));cut.WaitForAssertion(()=>Assert.NotEmpty(cut.FindAll("form")));cut.Find("input[maxlength='200']").Change("Yeni strateji");ctx.Api.Plan.Revision=99;cut.Find("form").Submit();cut.WaitForAssertion(()=>Assert.NotNull(ctx.Api.SavedRequest));Assert.Equal("Yeni strateji",ctx.Api.SavedRequest!.Name);Assert.Equal(7,ctx.Api.SavedRequest.ExpectedRevision);Assert.Contains("validate",ctx.Api.Calls);Assert.Empty(ctx.Api.StatusRequests);}
 [Fact] public void Invalid_definition_never_reaches_create_or_update(){using var ctx=new TrackingTestContext();ctx.Api.Invalid=true;var cut=ctx.Render<TrackingPlanEditor>(p=>p.Add(x=>x.Plan,ctx.Api.Plan));cut.WaitForAssertion(()=>Assert.NotEmpty(cut.FindAll("form")));cut.Find("form").Submit();cut.WaitForAssertion(()=>Assert.Contains("weight_total",cut.Markup));Assert.Null(ctx.Api.SavedRequest);}
 [Fact] public void Conflict_keeps_user_input_without_retry_or_silent_reload(){using var ctx=new TrackingTestContext();ctx.Api.SaveFailure=new PlatformApiException(HttpStatusCode.Conflict,"");var cut=ctx.Render<TrackingPlanEditor>(p=>p.Add(x=>x.Plan,ctx.Api.Plan));cut.WaitForAssertion(()=>Assert.NotEmpty(cut.FindAll("form")));cut.Find("input[maxlength='200']").Change("Kaybolmaması gereken ad");cut.Find("form").Submit();cut.WaitForAssertion(()=>Assert.Contains("eski sürümün üzerine yazılmadı",cut.Markup));Assert.Equal("Kaybolmaması gereken ad",cut.Find("input[maxlength='200']").GetAttribute("value"));Assert.Single(ctx.Api.Calls,x=>x=="save");Assert.DoesNotContain("plan",ctx.Api.Calls);}
 [Fact] public void Readonly_editor_rejects_submitted_mutation(){using var ctx=new TrackingTestContext();var cut=ctx.Render<TrackingPlanEditor>(p=>p.Add(x=>x.Plan,ctx.Api.Plan).Add(x=>x.ReadOnly,true));cut.WaitForAssertion(()=>Assert.NotEmpty(cut.FindAll("form")));Assert.True(cut.Find("fieldset.editor-fields").HasAttribute("disabled"));cut.Find("form").Submit();Assert.Null(ctx.Api.SavedRequest);}
 [Fact] public void Existing_live_mode_is_preserved_and_not_silently_downgraded(){using var ctx=new TrackingTestContext();ctx.Api.Plan.CurrentVersion!.Definition.Execution.Mode=TrackingExecutionMode.Live;var cut=ctx.Render<TrackingPlanEditor>(p=>p.Add(x=>x.Plan,ctx.Api.Plan));cut.WaitForAssertion(()=>Assert.NotEmpty(cut.FindAll("form")));cut.Find("form").Submit();cut.WaitForAssertion(()=>Assert.NotNull(ctx.Api.SavedRequest));Assert.Equal(TrackingExecutionMode.Live,ctx.Api.SavedRequest!.Definition.Execution.Mode);Assert.Empty(ctx.Api.StatusRequests);}
 [Fact] public void Draft_can_be_saved_while_scheduler_disabled_but_never_activated(){using var ctx=new TrackingTestContext();ctx.Api.SchedulerEnabled=false;var cut=ctx.Render<TrackingPlanEditor>();cut.WaitForAssertion(()=>Assert.NotEmpty(cut.FindAll("form")));cut.Find("input[maxlength='200']").Change("Taslak strateji");cut.FindAll("button").Single(x=>x.TextContent.Contains("Sepete ekle")).Click();cut.WaitForAssertion(()=>Assert.Contains("import",ctx.Api.Calls));cut.Find("form").Submit();cut.WaitForAssertion(()=>Assert.NotNull(ctx.Api.SavedRequest));Assert.Null(ctx.Api.SavedRequest!.ExpectedRevision);Assert.Empty(ctx.Api.StatusRequests);}
}
