using Bunit;
using Microsoft.AspNetCore.Components;
using XN1Lab.XN1Finance.PortfolioAnalytics.Web.Features.Tracking.Components;
using XN1Lab.XN1Finance.PortfolioAnalytics.Web.Features.Tracking.Models;
namespace XN1Lab.XN1Finance.Tracking.Tests;
public sealed class TrackingRuleEditorTests
{
 [Fact] public void Score_components_do_not_offer_self_referential_total_score(){using var ctx=new BunitContext();var cut=ctx.Render<TrackingValueEditor>(p=>p.Add(x=>x.Value,new TrackingValue{Kind=TrackingValueKind.Constant,Constant=30}).Add(x=>x.AllowTotalScore,false));Assert.DoesNotContain(cut.FindAll("option"),x=>x.GetAttribute("value")=="TotalScore");}
 [Fact] public void Entry_and_exit_operands_offer_total_score(){using var ctx=new BunitContext();var cut=ctx.Render<TrackingValueEditor>(p=>p.Add(x=>x.Value,new TrackingValue{Kind=TrackingValueKind.Constant,Constant=30}).Add(x=>x.AllowTotalScore,true));Assert.Contains(cut.FindAll("option"),x=>x.GetAttribute("value")=="TotalScore");}
 [Fact] public void Changing_operand_kind_removes_stale_incompatible_fields(){using var ctx=new BunitContext();TrackingValue? changed=null;var cut=ctx.Render<TrackingValueEditor>(p=>p.Add(x=>x.Value,new TrackingValue{Kind=TrackingValueKind.Constant,Constant=30}).Add(x=>x.ValueChanged,EventCallback.Factory.Create<TrackingValue>(this,x=>changed=x)));cut.Find("select").Change("Price");Assert.NotNull(changed);Assert.Equal(TrackingValueKind.Price,changed.Kind);Assert.Null(changed.Constant);Assert.Equal(TrackingTimeframe.Hour2,changed.Timeframe);}
 [Fact] public void Changing_comparison_to_all_wraps_and_preserves_the_existing_comparison(){using var ctx=new BunitContext();TrackingRule? changed=null;var original=new TrackingRule{Kind=TrackingRuleKind.Comparison,Left=new(){Kind=TrackingValueKind.Constant,Constant=1},Right=new(){Kind=TrackingValueKind.Constant,Constant=2},Comparison=TrackingComparison.LessThan};var cut=ctx.Render<TrackingRuleEditor>(p=>p.Add(x=>x.Rule,original).Add(x=>x.RuleChanged,EventCallback.Factory.Create<TrackingRule>(this,x=>changed=x)));cut.Find("select").Change("All");Assert.NotNull(changed);Assert.Equal(TrackingRuleKind.All,changed.Kind);Assert.Null(changed.Left);Assert.Null(changed.Right);Assert.Null(changed.Comparison);var child=Assert.Single(changed.Children);Assert.Same(original,child);Assert.Equal(1,child.Left?.Constant);Assert.Equal(2,child.Right?.Constant);Assert.Equal(TrackingComparison.LessThan,child.Comparison);}
 [Fact] public void Switching_all_to_any_preserves_children_and_operand_values(){using var ctx=new BunitContext();TrackingRule? changed=null;var child=new TrackingRule{Kind=TrackingRuleKind.Comparison,Left=new(){Kind=TrackingValueKind.Indicator,IndicatorBindingKey="rsi2h"},Right=new(){Kind=TrackingValueKind.Constant,Constant=30},Comparison=TrackingComparison.LessThan};var original=new TrackingRule{Kind=TrackingRuleKind.All,Children=[child]};var cut=ctx.Render<TrackingRuleEditor>(p=>p.Add(x=>x.Rule,original).Add(x=>x.RuleChanged,EventCallback.Factory.Create<TrackingRule>(this,x=>changed=x)));cut.Find("select").Change("Any");Assert.Same(original,changed);Assert.Equal(TrackingRuleKind.Any,changed!.Kind);var preserved=Assert.Single(changed.Children);Assert.Same(child,preserved);Assert.Equal("rsi2h",preserved.Left?.IndicatorBindingKey);Assert.Equal(30,preserved.Right?.Constant);}
 [Fact] public void Readonly_rule_does_not_mutate_even_when_an_event_is_dispatched(){using var ctx=new BunitContext();var mutations=0;var cut=ctx.Render<TrackingRuleEditor>(p=>p.Add(x=>x.Rule,new TrackingRule{Kind=TrackingRuleKind.Comparison}).Add(x=>x.ReadOnly,true).Add(x=>x.RuleChanged,EventCallback.Factory.Create<TrackingRule>(this,_=>mutations++)));Assert.True(cut.Find("fieldset").HasAttribute("disabled"));cut.Find("select").Change("Any");Assert.Equal(0,mutations);}
}
